Counterparty offer
ricequant/rqalpha pull request #637
Opened 2021-06-08 09:48 UTC by mar-heaven

2021-06-11 04:11 UTC, Cuizi7 requested changes

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +    def match(self, account, order, open_auction, unfilled_quantity=0, n=1):
match 是基类定义的接口，子类的方法签名应与基类保持一致

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +                if len_turnover > n:
len_turnover > n 是在什么情况下出现的？

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +        self._trade_order_book_id = None
这个属性是做啥用的？

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +            self._turnover[order.order_book_id][-1] += min(amount, fill)
self._turnover 用的太诡异了，直接初始化成固定长度的 list 或者用字典会不会更舒服？

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +        if order.type == ORDER_TYPE.MARKET and order.unfilled_quantity != 0:
市价单只能参与一档撮合是产品提出的需求吗？

2021-06-11 04:11 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py
> +                                                               MATCHING_TYPE.COUNTERPARTY_OFFER]
立即撮合有点奇怪，这里也是产品给的需求吗？

2021-06-11 10:05 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py
> +                                                               MATCHING_TYPE.COUNTERPARTY_OFFER]
"当前 tick 立即撮合"

2021-06-11 10:34 UTC, Cuizi7 requested changes

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/interface.py
> +        获取合约的1-5档卖价
获取合约的多档卖方神报价

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +            MATCHING_TYPE.COUNTERPARTY_OFFER: lambda order_book_id, side, n: self._env.price_board.get_price_by_side(
这一行是不是可以去掉

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> -            MATCHING_TYPE.NEXT_TICK_BEST_COUNTERPARTY: lambda order_book_id, side: (
为啥把 best_counterparty 删了

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +                self.match(account, order, open_auction)
有可能走到这个分支吗？
市价单 order.quantity 应该不会为0？
限价单 self._a_volume[order_book_id][0] 为 0 的情况上边应该已经处理过了？

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +            order._avg_price = 0
上文已经排除了成交价和成交量为 nan 的情况，avg_price 应该也不可能为 nan？

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +        order_book_id = event.tick.order_book_id
这里会针对所有已订阅合约执行操作，太浪费了，大部分合约可能并不会发单

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py
> +                                                               MATCHING_TYPE.COUNTERPARTY_OFFER]
这里的“当前tick”是有歧义的，如果在合约 A 的 handle_tick 下发了合约 B 的订单，合约 B 不存在“当前 tick”。
这里需要和产品再次确认一下需求，我建议所有针对 tick 的撮合都实现为下一个 tick 撮合

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/model/order.py
> +    def frozen_cash(self):
订单状态变动的时候 frozen_cash 也需要更新

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/portfolio/account.py
> +            self._frozen_cash -= order.frozen_cash
下文 apply_trade 中也有解冻资金的逻辑

2021-06-11 10:34 UTC, Cuizi7 commented on rqalpha/portfolio/account.py
> +            self._frozen_cash -= order.frozen_cash
也需要做对应改动

2021-06-15 02:55 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +        self._trade_order_book_id = None
去掉了

2021-06-15 02:55 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +            self._turnover[order.order_book_id][-1] += min(amount, fill)
已重写

2021-06-15 02:56 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py
> +                                                               MATCHING_TYPE.COUNTERPARTY_OFFER]
已从_match_immediately中移出

2021-06-15 02:56 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +        order_book_id = event.tick.order_book_id
放到了match中加载

2021-06-15 03:00 UTC, mar-heaven commented on rqalpha/mod/rqalpha_mod_sys_simulation/matcher.py
> +    def match(self, account, order, open_auction, unfilled_quantity=0, n=1):
一致了

2021-06-15 08:23 UTC, merged