期货回测新增时序交易参数功能
ricequant/rqalpha pull request #835
Opened 2023-12-27 05:37 UTC by Lin-Dongzhao

2023-12-27 09:58 UTC, Cuizi7 requested changes

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                    df['commission_type'] = [self.change_commission_type(v) for v in df['commission_type']]
同样效率低，尽量避免在列里迭代调用函数

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                            h5.create_dataset(order_book_id, data=data)
这里是测过了 create 新 dataset 相比 append 进去效率更高嘛？

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +def update_futures_trading_parameters(path, futures_trading_parameters_config):
尽量避免这种字典参数，调用方看到这样的函数签名都不知道该怎么用这个函数

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/model/instrument.py
> +    def __init__(self, dic, future_tick_size_getter=None, future_long_margin_ratio_getter=None, future_short_margin_ratio_getter=None):
注意期货的英文是 futures，之前代码中的“future”是错误的，新的代码更正过来。

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/model/instrument.py
> +        if self.type == INSTRUMENT_TYPE.FUTURE:
这个判断是不是可以省掉，非期货的直接传入一个 lambda: 1 就可以了。

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/model/instrument.py
> +        # type: (float, float, float, POSITION_DIRECTION) -> float
quantity 是 int

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +    def get_futures_trading_parameters(self, instrument, dt):
用 annotation 标注一下返回值类型

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +    def get_futures_trading_parameters(self, instrument, dt):
最好能养成用 annotation 标注参数和返回值类型的习惯。

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    @lru_cache(1024)
参数 instrument 是 hashable 的吗？

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
>          self._future_info = {}
self._future_info 是不是可以去掉了

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    def to_namedtuple(self, info):
字段都是确定的，直接用 FuturesInfo 的构造函数构造一个结构就可以了，不用搞这么多if else

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    FuturesInfo = collections.namedtuple("FuturesInfo", [
这个类型是会被外部代码使用的，不要定义在类内部。

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    FuturesTradingParameters = collections.namedtuple("FuturesTradingParameters", [
这跟上边  FuturesInfo 不是几乎是同一个类么？

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +        self.futures_trading_parameters = self.FuturesTradingParameters._make(parameter_data_list)
应该通过函数返回值传递的东西这么搞到对象属性里去了？

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +        self._order_book_id = instrument.order_book_id
order_book_id 应该是局部变量，怎么也搞到对象属性里去了

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +                    raise
语法错误

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +                if dt in range(
直接比大小就可以了

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +        if "margin_rate" not in self._future_info_store._default_data[list(self._future_info_store._default_data.keys())[0]]:
不要调用私有属性

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/interface.py
> +    def get_commission_info(self, instrument, dt):
这个方法可以砍掉了吧，保留一个   get_futures_trading_parameters 即可。

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/interface.py
> +    def get_futures_trading_parameters(self, instrument, dt):
参数直接用 order_book_id 是不是更好一些，避免在 order_book_id 和 instrument 之间转来转去

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/main.py
> +        is_init = init_rqdatac(getattr(config.base, 'rqdatac_uri', None))
is_init -> rqdatac_enabled

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_accounts/position_model.py
>      @cached_property
margin 如果会随着时间变化这里就不能 cache 了

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_accounts/position_model.py
>      @cached_property
不如订阅一个事件来每日更新吧，要不然每次都要调用 instrument 的方法性能堪忧

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +        with h5_file(self._path) as h5:
把单个合约完整的时间序列缓存起来，避免每次都 IO

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +            if trading_parameters == None:
is None

2023-12-27 09:58 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    FuturesInfo = collections.namedtuple("FuturesInfo", [
用 typing.NamedTuple 吧，要不然搞不清楚每个字段是什么类型

2023-12-27 10:36 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +    if rqdatac.__version__ < '2.11.11.4':
在tqalpha.main中有对环境是否已安装rqdatac进行了验证，如果没有则没法进入到当前的步骤，是否还需要在这里进行验证

2023-12-28 02:07 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +    if rqdatac.__version__ < '2.11.11.4':
哦，那可以不验证了

2023-12-28 10:06 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +            need_create_h5 = True
代码更新后的的数据更新逻辑中将不需要在这一步做检验，已删除相应代码

2023-12-28 10:09 UTC, Lin-Dongzhao commented on rqalpha/interface.py
> +    def get_futures_trading_parameters(self, instrument, dt):
这里传入的就是一个 instrument 的对象，而非单纯的 order_book_id ，实际运行的函数里有用 instrument 的其他属性做判断，所以这里还是用 instrument 好一些

2024-01-02 06:03 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +                            h5.create_dataset(order_book_id, data=data)
测试发现两个方法效率差不多，但是 create 新 dataset 效率会稍微高一些

2024-01-09 11:47 UTC, Cuizi7 requested changes

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                                    [tuple(i) for i in chain(h5[order_book_id][:], df.loc[order_book_id].to_records())],
不需要构造 list

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    order_book_id: str = None
Optional[str]

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +        if "margin_rate" not in self._default_data[list(hard_code.keys())[0]]:
list(...)[0] -> next(iter(...))

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +            for id_or_syms in list(self._default_data.keys()):
for ... in self._default_data:

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +                if len(id_or_syms) <= 2:
最好用一个正则表达式

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +        futures_trading_parameters = FuturesTradingParameters(
FuturesTradingParameters(**arr[0])

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    tick_size: float = None
砍掉

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/data_proxy.py
> +    def get_futures_trading_parameters(self, order_book_id):
还是传dt进来吧

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/storages.py
> +    def data_compatible(self, futures_instruments_store):
改成在  __init__ 中调用

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +    def get_futures_trading_parameters(self, instrument):
@lru_cache

2024-01-09 11:47 UTC, Cuizi7 commented on rqalpha/model/instrument.py
> +    def long_margin_ratio(self):
@lru_cache
def get_long_margin_ratio(self, dt)

2024-01-12 08:20 UTC, Cuizi7 requested changes

2024-01-12 08:20 UTC, Cuizi7 commented on rqalpha/data/base_data_source/data_source.py
> +    def get_futures_trading_parameters(self, instrument, dt):
这里在加一层 lru_cache 吧

2024-01-12 08:20 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_accounts/position_model.py
>      def margin_rate(self):
instrument 里有 lru_cache 了，这里的缓存可以去掉了

2024-01-15 05:57 UTC, merged