Rqsdk 729
ricequant/rqalpha pull request #856
Opened 2024-03-13 09:43 UTC by Lin-Dongzhao

2024-03-13 10:03 UTC, Cuizi7 requested changes

2024-03-13 10:03 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +    def auto_update_task(self, filename, instrument, rqdata_api, fields):
后三个参数似乎每次调用都是一样的，应该更适合作为类属性？

2024-03-13 10:03 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +    def auto_update_task(self, filename, instrument, rqdata_api, fields):
然后 get 操作是不是也可以封装进这个类：get(instrument, trading_dt)

2024-03-14 09:40 UTC, Cuizi7 requested changes

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +            df = pd.concat([df, eval(command)])
eval一个外部传入的字符串是很危险的操作，可以直接让外部传入一个 rqdatac 的函数？

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +            command = "rqdatac.{}(dic['order_book_id'], dic['start_date'], dic['end_date'], {})".format(self._rqdata_api, self._fields)
这 dic 是哪来的变量？

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +    def _get_dominant_df(self, command, underlying_symbol, start_date):
话说这个操作是什么目的

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                if instrument.type in [INSTRUMENT_TYPE.FUTURE, INSTRUMENT_TYPE.OPTION]:
这里是不是可以不区分品种，所有品种都直接获取交易日

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +    def _update_datetime(self, dt):
DataProxy 由 get_trading_dt 方法，是否可以直接调用

2024-03-14 09:40 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                df['datetime'] = df[time_parameter].map(convert_date_to_date_int)
既然字段实际上是交易日，字段名也改成 trading_dt 或者 trading_date 吧

2024-03-15 03:31 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +    def _get_dominant_df(self, command, underlying_symbol, start_date):
获取主力连续合约的数据需要用到

2024-03-15 07:07 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +            data = data[data['datetime'] == dt]
经测试使用 searchsorted 效率会快上一倍，updated

2024-03-15 07:08 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +            h5 = h5py.File(self._file, "w")
updated

2024-03-15 07:08 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +                raise OSError("File {} update failed, if it is using, please update later, "
updated

2024-03-15 07:08 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +                if datetime.date.today() == last_date or rqdatac.get_previous_trading_date(datetime.date.today()) == last_date:
原本的判断逻辑存在问题，已修改，数据会更新至今日

2024-03-15 07:08 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +            df = pd.concat([df, eval(command)])
updated

2024-03-15 07:10 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +            command = "rqdatac.{}(dic['order_book_id'], dic['start_date'], dic['end_date'], {})".format(self._rqdata_api, self._fields)
原本用于获取主力连续合约时需要用到（一开始使用 rqdatac 无法直接获取主力连续合约的 open_auction_info 数据），经确认是bug，数据那边会修复主力连续合约的数据，该部分代码现删除

2024-03-15 07:10 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +    def _get_dominant_df(self, command, underlying_symbol, start_date):
同上

2024-03-15 07:11 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +                if instrument.type in [INSTRUMENT_TYPE.FUTURE, INSTRUMENT_TYPE.OPTION]:
修改为如果是股票就不去获取交易日（考虑到股票的时间跨度比较长，没必要在这里浪费一点时间）

2024-03-15 07:12 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +    def _update_datetime(self, dt):
已修改为使用该方法（data_proxy._data_source.get_future_trading_date）

2024-03-15 07:12 UTC, Lin-Dongzhao commented on rqalpha/data/bundle.py
> +                df['datetime'] = df[time_parameter].map(convert_date_to_date_int)
updated

2024-03-15 07:47 UTC, Cuizi7 requested changes

2024-03-15 07:47 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +        # type: (str, str, function, List[str]) -> None
function ❌
Callable ✅

2024-03-15 07:47 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +            self.rqdata_init = True
这属性没用到？

2024-03-15 07:47 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                h5 = h5py.File(self._file, "a")
似乎不用区分文件是否存在？可以一律用 a

2024-03-15 07:47 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                    if start_date > datetime.date.today():
用 end_date

2024-03-15 07:50 UTC, Cuizi7 requested changes

2024-03-15 07:50 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +        if not (df is None or df.empty):
尝试一下直接 allocate 一个 array，然后从 df 里把数据 copy 到 array，避免过多的 DataFrame 操作

2024-03-15 07:50 UTC, Cuizi7 commented on rqalpha/data/bundle.py
> +                df[time_parameter] = df[time_parameter].map(self._env.data_proxy._data_source.get_future_trading_date)
尝试一下直接对 array 做 get_trading_dt 操作

2024-03-19 05:44 UTC, merged