Rqsdk 735
ricequant/rqalpha pull request #858
Opened 2024-03-20 03:04 UTC by Lin-Dongzhao

修复期货交割时 trading_pnl 计算问题

2024-03-20 03:24 UTC, Cuizi7 requested changes

2024-03-20 03:24 UTC, Cuizi7 commented on tests/test_f_delivery.py
这测试一个 assert 都没有，至少验证一下交割之后的 quantity total_value pnl 之类的字段。

2024-03-21 10:20 UTC, Cuizi7 requested changes

2024-03-21 10:20 UTC, Cuizi7 commented on rqalpha/mod/rqalpha_mod_sys_accounts/position_model.py
> +                None, self._last_price, self._quantity, side, POSITION_EFFECT.CLOSE, self._order_book_id
用 self.last_price 吧

2024-03-21 10:20 UTC, Cuizi7 commented on rqalpha/utils/testing/fixtures.py
> +from rqalpha.main import init_rqdatac
这句似乎没用

2024-03-21 10:20 UTC, Cuizi7 commented on tests/unittest/test_data/test_auto_update_bundle/test_auto_update_bundle_mixin.py
> +        self._path = os.path.abspath(os.path.expanduser('~/.rqalpha/bundle'))
这里给个临时目录吧，用 tempfile module

2024-03-21 10:55 UTC, Lin-Dongzhao commented on rqalpha/utils/testing/fixtures.py
> +from rqalpha.main import init_rqdatac
中间某个版本加上的，忘记删掉

2024-03-22 03:52 UTC, merged